[package]
name = "syconfig"
version = "0.1.0"
edition = "2021"
authors = ["Symphony Team"]
description = "Configuration management for Symphony"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"