// monacoOptions.js
export const defaultMonacoOptions = {
	fontSize: 14,
	fontFamily: "Consolas, 'Courier New', monospace",
	cursorBlinking: "smooth",
	cursorSmoothCaretAnimation: true,
	minimap: { enabled: true },
	lineHeight: 20,
	renderWhitespace: "selection",
	automaticLayout: true,
	glyphMargin: true,
	folding: true,
	foldingHighlight: true,
	foldingImportsByDefault: true,
	showFoldingControls: "always",
	links: true,
	multiCursorModifier: "ctrlCmd",
	multiCursorMergeOverlapping: true,
	mouseWheelZoom: true,
	smoothScrolling: true,
	fastScrollSensitivity: 5,
	wordWrap: "on",
	wordBasedSuggestions: true,
	occurrencesHighlight: true,
	selectionHighlight: true,
	matchBrackets: "always",
	autoClosingBrackets: "always",
	autoClosingQuotes: "always",
	autoIndent: "full",
	tabSize: 2,
	renderLineHighlight: "all",
	formatOnType: true,
	formatOnPaste: true,
	insertSpaces: true,
	quickSuggestions: { other: true, comments: false, strings: true },
	parameterHints: { enabled: true },
	hover: { enabled: true },
	suggestOnTriggerCharacters: true,
	acceptSuggestionOnEnter: "on",
	snippetSuggestions: "inline",
	inlineSuggest: { enabled: true },
	gotoLocation: {
		multipleDefinitions: "peek",
		multipleReferences: "peek",
		multipleDeclarations: "peek",
	},
	definitionLinkOpensInPeek: true,
	guides: { bracketPairs: true },
};
