[package]
name = "sykitregistry"
version = "0.1.0"
edition = "2021"
authors = ["Symphony Team"]
description = "Extension discovery and registration for Symphony Orchestra Kit"
license = "MIT"

[dependencies]