[package]
name = "sykitmanifest"
version = "0.1.0"
edition = "2021"
authors = ["Symphony Team"]
description = "Manifest processing for Symphony Orchestra Kit"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"