[package]
name = "syipcprotocol"
version = "0.1.0"
edition = "2021"
authors = ["Symphony Team"]
description = "Message serialization for Symphony IPC"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }