[package]
name = "sytypes"
version = "0.1.0"
edition = "2021"
authors = ["Symphony Team"]
description = "Core type definitions for Symphony"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }