[package]
name = "syconbindings"
version = "0.1.0"
edition = "2021"
authors = ["Symphony Team"]
description = "PyO3 bindings for Symphony Conductor"
license = "MIT"

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }